### ISSUE TITLE
Fix or Improve behavior of LB master endpoints when no DNS is in play

### ISSUE THREAD

**Issue by javaboyuk** [apprenda/kismatic#123]
The entries for are wrong:
The newbie of kismatic is lead a merry dance....
```
update_hosts_files: true            # When true, the installer will add entries for all nodes to other nodes' hosts files. Use when you don't have access to DNS.
load_balanced_fqdn: "master-1"                 # If using a load balanced master fqdn enter it here; otherwise use the fqdn of any master node.
load_balanced_short_name: "master-1"           # If using a load balanced master enter its short name here; otherwise use the short name of any master node.
```
The above would suggest you can run without DNS, and use names resolved by /etc/hosts. BUT YOU CAN NOT! 

Why....
kube-dns is setup NOT to mount /etc/hosts into the container and so never starts failing on looking up with dns "master-1" (in this example) which 8.8.8.8 (in my case) can never resolve correctly.

TO FIX I have done the following:
load_balanced_fqdn: "10.10.0.21"    

ie setting it to the actual IP of my first apimaster node. I assume you could put in the IP address of the Load-balancer too ? however would the certs be created for it?

**Comment by dasmb** [comment]
What you're describing sounds related to an issue that @dkoshkin may have fixed in 1.0.2. I'll let him chime in here because if it isn't, we should consider mounting /etc/hosts as you suggest.

In any case, it sounds like we need to clean up that description of the "update_hosts_files" flag as it's less magical than it purports to be.
