### ISSUE TITLE
Destroy/uninstall workflow

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#141]
Currently, there is no way to undo all the changes performed by kismatic on the machines. This isn't too valuable in cloud infrastructure, but is probably valuable for bare-metal.

**Comment by codymccain** [comment]
Since we treat k8s nodes as "cattle" rather than "pets", uninstallation of k8s should simply be re-imaging a machine, even bare hardware.  Since containers can run in privileged mode, it is impossible to know all the changes that have been made to a machine.  If a user wants to assume the risk of other changes, the RPMs can be removed.  It might be useful if kismatic cli tool provided a mechanism to remove all RPMs installed on a node as well as docker images and containers present on a node.

**Comment by dasmb** [comment]
We could probably figure out a way to remove kismatic. The question is: would that be actually valuable to anyone, and what form should it take?

Calico will alter iptables, KET will alter Hosts files. Are these included in the cleanup? Finding subsequent user mods to these records after installation can be tricky to preserve.

Once kismatic is installed, user workloads can have pretty dramatic effects on a machine -- at the very least writing persistent data and evoking system logs in ways we can't predict and don't journal, but also possibly launching processes or otherwise modifying machine configuration.

Just like with a regular operating system, the safest way to handle removal of a data center operating system is to start from scratch.

**Comment by alexbrand** [comment]
Closing for now.
