### ISSUE TITLE
Introduce upgrade integration suite

### ISSUE THREAD

**Issue by dasmb** [apprenda/kismatic#266]
An upgrade integration suite would test some subset of the permutations of

all source versions * all supported OSs * interesting deployment models

for each potential release candidate of Kismatic.

**Comment by dkoshkin** [comment]
### What To Test
* Currently there has been 9 prior releases of `kismatic` - is testing required for all versions?  Perhaps testing the latest patch version for each minor is sufficient: `v1.0.3`, `v1.1.1` and `v1.2.2`
* Officially support 3 OSs `Ubuntu16.04` and `CentOS7` and `RHEL7` 
  `CentOS7` and `RHEL7` can be reduced to just testing with since there are no major differences that would impact the upgrade

#### Major features to verify after an upgrade
- [ ] Minikube
- [ ] Hosts file
- [ ] Docker registry: external and internal
- [ ] Offline install 
- [ ] Master HA
- [ ] Ingress
- [ ] GlusterFS storage
- [ ] NFS 
- [ ] Add worker
- [ ] DNS - already covered by the smoke tests after each upgrade
- [ ] Dashboard

Testing each feature for each OS for each previous version would grow the suite quickly and is not necessary.

### How To Test
* Manually triggered in CI
* Use a single OS to test "features"

**Comment by alexbrand** [comment]
Test suite introduced under `integration/upgrade_test.go`
