### ISSUE TITLE
API server unable to contact new worker node

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#504]
@xetys ran into an issue after adding a new worker. The worker was added using `apply`, but any attempts to get logs from containers running on that node would fail with:
```
Get https://minion03:10250/containerLogs/kloud/uaa-2391481347-9pn66/uaa-app?timestamps=true: 
dial tcp: lookup minion03 on 185.48.116.10:53: no such host
```

**Comment by dkoshkin** [comment]
I was able to also reproduce this error when using the `kismatic install add-worker` command.

The issue is that we modify the `/etc/hosts` file but those changes are not picked up by the API server.

Some options:
- Mount `/etc/hosts` file
- Trigger an API server restart 
- Modify the `/etc/hosts` file in the pod directly
