### ISSUE TITLE
Update docker version

### ISSUE THREAD

**Issue by alirezaDavid** [apprenda/kismatic#513]
Can i update explicity docker version and change this `docker_engine_apt_version: 1.11.2-0~xenial` variable?

Thanks.

**Comment by dkoshkin** [comment]
@alirezaDavid what version of Docker were you looking at, what are some features you are looking at thats available in other versions?
Just trying to understand if we should upgrade the version in core.

**Comment by alirezaDavid** [comment]
I want docker to 1.12.6.
Just for sake of upgrading :)
I try kismatic with 1.12.6 and ping you with results.

**Comment by xbernpa** [comment]
Because of this issue : https://github.com/moby/moby/issues/21848

Docker with a Kubernetes-Kismatic install makes docker to fill /var/log/messages 

---
Apr 26 13:42:59 hostnamestripped docker: time="2017-04-26T13:42:59.978778806-04:00" level=error msg="collecting stats for 61edd5715977cf24b0859814a7b5f61a058033e2c49fab0c06c158a8a79cd052: invalid id: "
---

On centos 7 docker-engine version is 1.12.6-1.0.3.el7 so updating docker-engine to version 1.12 would fix the issue within a kismatic install.

**Comment by akdj** [comment]
Hi, 

I need to use v1.12 or higher of Docker too, it seems to be required for using hyperledger fabric.
