### ISSUE TITLE
Custom CA certificate

### ISSUE THREAD

**Issue by altvnk** [apprenda/kismatic#544]
Does Kismatic supports usage of previously generated CA for certificate generation. What I can see is that existing certificates are leaved untouched after complete reinstall (`generated` folder wasn't deleted)

And I'm also wondering if it's possible to change all certificates on running cluster (including offline mode) in case when they was freshly generated.

**Comment by alexbrand** [comment]
Hey @altvnk 

Yes, you can bring your own CA certificate for generating the rest of the certs. You may even bring your own certs if you like. Currently, the way to do this is to place them in the `generated/keys` directory so that we can pick them up.

We don't have a cert rotation feature at the moment.

**Comment by altvnk** [comment]
Sweet, it worked for me. Thanks!
