### ISSUE TITLE
Distribution should have a version-specific directory at its root

### ISSUE THREAD

**Issue by ChrisNelsonPE** [apprenda/kismatic#60]
When I untarred `kismatic.tar.gz` I was surprised to find `kismatic` and a couple of directories in my working directory.  I am accustomed to seeing something like `./ket-1.0.0/` as the top level of the tar so when I get 1.0.1 or something, I can untar without clobbering my existing files.

**Comment by dasmb** [comment]
At the moment, KET is intended to manage a single cluster, and keeps some cluster state around (execution history, PKE primitives and machine inventories) in its subdirectories. We intend to move this cluster state into the cluster as soon as we have a means of managing persistent state within a cluster, and then KET versions will be something that is safer to move as a 

Because of this state storage, it wouldn't be ideal to release into a versioned directory. Besides which, it is potentially dangerous to keep older versions of KET around...were you to accidentally use an earlier version to, say, add nodes to a cluster that was built from a later version, you might be missing out on reliability fixes or assert the wrong versions of software.

You are welcome to unpack KET wherever you like. I would suggest not a versioned folder but a folder specific to your cluster.

**Comment by pires** [comment]
Is the behavior detailed above documented?

**Comment by dasmb** [comment]
Not in depth, but the importance of the install directories and the machine they run on to future modifications to a cluster is highlighted in several areas.

**Comment by alexbrand** [comment]
Due to reasons outlined in the above comments (mainly https://github.com/apprenda/kismatic/issues/60#issuecomment-259497100), we will not address this at this point. Closing.
