### ISSUE TITLE
Proxy e2e test is failing with helm issue

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#762]
The proxy e2e test is fails with the following error:

```
- Running task: run helm init
  ip-10-0-3-75                                                                  [OK]
- Running task: add kismatic helm repo
  ip-10-0-3-75                                                                  [ERROR]
---- STDERR ----
Error: Looks like "https://apprenda.github.io/kismatic-charts/" is not a valid chart repository or cannot be reached: Get https://apprenda.github.io/kismatic-charts/index.yaml: proxyconnect tcp: dial tcp 10.0.3.250:3128: getsockopt: no route to host
---------------
Initialize Helm and Start Tiller Finished
error installing: error running playbook: error running ansible: exit status 2
```

It is interesting that the helm init step did not fail, as it also should have attempted to go through the proxy.

Failure from:
https://circleci.com/gh/apprenda/kismatic/670?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack

**Comment by dkoshkin** [comment]
The reason `helm init` did not fail is because the `~/.helm` directory already existed on the machine from a pervious test and `helm` did not try to connect to the URL.

I've been thinking about the underlying issue, there are 2 unique configurations a user may have with a proxy.
a) All the machines, including the install machine have the proxy configured. 
b) The cluster nodes but not the install machine have the proxy configured. 

Originally, KET did not use the proxy settings when running `helm` which works fine for `b` but not `a`, this was fixed in https://github.com/apprenda/kismatic/issues/735. However this broke the integration test that uses configuration `b`.

KET will not know what configuration its running on and will not really know when to use proxy settings and when not to. 

The safest thing is to leave the code how it is, and document that when running an install in configuration `b` the user should add `https://apprenda.github.io/kismatic-charts/` and `https://apprenda.github.io/kismatic-charts/` in the plan file under `no_proxy`. 

In configuration `a` it would be up to the operator to configure the proxy properly to be able to connect to the 2 URLs above.

Another option is to have a new flag in the plan file, this would skip the configuration of the `helm` client on the install machine and it would would no longer cause this issue. (This is something similar that is already being done for disconnected installs)
```
package_manager
  package_manager:
    options:
      helm:
        configure_client: true      # Options: true/false
```

**Comment by dkoshkin** [comment]
A preflight will be added to check connections to the required URLs from the install node.
