### ISSUE TITLE
Remove ABAC authorization mode

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#778]
For the next minor release, we should remove the ABAC authorization mode, which has been deprecated since we introduced RBAC.

**Comment by flyer103** [comment]
Hi, will this feature be planed to be released in the near future?

**Comment by magowant** [comment]
We investigated disabling ABAC but immediately found issues, highlighting that the KET deployment of K8s is still heavily reliant on ABAC. 

For example, the kube-dns deployment is still using the default service account, which is restricted in RBAC only mode, effectively breaking kube-dns. Applying the principle of least privilege, rather than make the default service account more permissive, specific service accounts should be used for each component that needs access to the K8s API:

kube-proxy *
kube-scheduler *
kube-controller-manager *
kube-dns *
calico-node
calico-kube-controllers
tiller
rescheduler
ingress
others?

Some of the core kube-system components (*) already have specific service accounts made available by default. See https://kubernetes.io/docs/admin/authorization/rbac/#service-account-permissions. The others components will need to have service accounts created as part of the KET install.

**Comment by swade1987** [comment]
Hey @magowant 

Thanks for this, you may be interested in https://github.com/apprenda/kismatic/pull/864 

This contains the work @dkoshkin has been doing regarding RBAC.

**Comment by willvrny** [comment]
@alexbrand @magowant @swade1987 We will probably need service accounts for the components. One strategy is to create Roles/ClusterRoles with no permissions. Check for API requests failures and slowly enable permissions. This ensures that only the necessary capabilities are enabled.

It seems that some of the existing charts online are too permissive.

**Comment by dkoshkin** [comment]
Closed in #864
